🚀  Add maven-publish plugin
LunabeeStudio/Lunabee_Compose_Android pull request #2
Opened 2022-04-21 09:04 UTC by hbernardi-luna

## 📜 Description
Configure project `LbcTopAppBar` in order to deploy it on Sonatype and Maven central.
Additional documentation [here](https://www.notion.so/lunabeestudio/Lunabee-Android-Compose-bb08d8a58b4e46f1bce9394aa7b3b8ed)

I also removed all the Composable Preview from the project (as I think it is useless for the Demo App as it is already a preview, and for the library it will avoid to add unnecessary and unwanted dependencies).

## 💡 Motivation and Context
Publish the first library on Maven Central

## 💚 How did you test it?
Deploy the library here https://search.maven.org/artifact/studio.lunabee.compose/lbctopappbar
And on Snapshot repositories https://s01.oss.sonatype.org/content/repositories/snapshots/

Use implementation("studio.lunabee.compose:lbctopappbar:_") instead of     implementation(project(Modules.lbctopappbar)) in demo app.

## 📝 Checklist
* [x] I compiled before submitting the PR
* [ ] I reviewed the submitted code
* [ ] I launched `./gradlew detekt`

2022-04-26 12:00 UTC, rlatapy-luna requested changes

2022-04-26 12:00 UTC, rlatapy-luna commented on buildSrc/src/main/kotlin/studio/lunabee/library/PublishingExt.kt
> +        }
Move to gradle properties, or use publisher?

2022-04-26 12:00 UTC, rlatapy-luna commented on versions.properties
> +# Copyright � 2022 Lunabee Studio
🤔

2022-04-26 12:00 UTC, rlatapy-luna commented on versions.properties
> +# Copyright � 2022 Lunabee Studio
🤔

2022-05-02 16:29 UTC, hbernardi-luna commented
@rlatapy-luna Configuration on Team City should be OK! I added a trigger to develop and master for the `Publish Library` job.

2022-05-02 21:58 UTC, rlatapy-luna approved these changes
![StratisStraxGIF](https://user-images.githubusercontent.com/45555889/166334132-a5e0b443-b373-42ce-b2b6-d84f4de02a74.gif)

2022-05-02 21:58 UTC, rlatapy-luna commented on buildSrc/src/main/kotlin/studio/lunabee/library/PublishingExt.kt
> +        }
Move to gradle properties, or use publisher?

2022-05-02 21:59 UTC, merged